# Generated by Django 4.0.3 on 2022-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qwrt',
            field=models.BooleanField(default=False),
        ),
    ]
