# Generated by Django 4.0.3 on 2022-03-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_qwrt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qwrt',
        ),
        migrations.AddField(
            model_name='user',
            name='departure',
            field=models.BooleanField(default=False),
        ),
    ]
