# Generated by Django 4.0.3 on 2022-03-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_qwrt_user_departure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='departure',
        ),
    ]
